# Generated by Django 3.0.6 on 2020-05-25 02:28

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('activity_type', models.CharField(choices=[(programs.models.ActivityType['HTML'], 'html'), (programs.models.ActivityType['MULT_CHOICE'], 'multiple_choice')], max_length=100)),
                ('html_snippet', models.TextField(null=True)),
                ('question', models.TextField(null=True)),
                ('options', models.ManyToManyField(related_name='activities_options', to='programs.Option')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('activities', models.ManyToManyField(related_name='sections_activities', to='programs.Activity')),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sections', models.ManyToManyField(related_name='programs_sections', to='programs.Section')),
            ],
            options={
                'db_table': 'programs',
            },
        ),
    ]
